### ISSUE TITLE
Element.closest polyfill

### ISSUE THREAD

**Issue by vicb** [realiarthur/lite-form#6]
While working on #5 I have noticed that lite-form [polyfills](https://github.com/realiarthur/lite-form/blob/master/src/utils.js#L34) `Element.closest`.

This seems to be mainly for [IE <= 11](https://caniuse.com/?search=element.closest).

Do you think this can be dropped ? (Adding a note in the documentation to add an external polyfill if IE support is required).

If you prefer to keep built-in IE11 support, would it make sense to create a `closest(element, selector)` function that do not polyfill `Element.closest()` ? I don't think there is a real need to update the `Element` proto and I think not modifying built-in protos could be better.

What do you think ?

**Comment by realiarthur** [comment]
I need ie11 support in my projects, so that’s why I implement it.

From other side, I think builtin function is better to use, than js
function. That’s why I add this functionality to prototype only if it not
there.

It makes some problem for typescript?

**Comment by vicb** [comment]
Yes the polyfill has some typing errors.

I didn't really investigate as I thought that it's not the job of a lib to polyfill but an external polyfill would be better.

If needed the polyfill errors could probably be fixed.

**Comment by realiarthur** [comment]
That’s make sense. I agree, this is not job for lib. Only need to write
about it and ie11 in readme
